added more configuration options
- added options for indicating repository name
- included option for changing the docker registry url
- modified force build tag to automatically bump minor version
- updated readme with relevant changes

[force build]

diff --git a/scripts/ci/build b/scripts/ci/build
--- a/scripts/ci/build
+++ b/scripts/ci/build
@@ -20,15 +20,29 @@ if [[ $? != "0" ]]; then
   printf "[ERROR] ${SETUP_DIR}/${TAG_NAME}.Version could not be found.\n";
   exit 1;
 fi;
+printf "NODE_VERSION:           ${NODE_VERSION}\n";
 
 YARN_VERSION="$(cat ${SETUP_DIR}/yarn.Version)";
 if [[ $? != "0" ]]; then
   printf "[ERROR] ${SETUP_DIR}/yarn.Version could not be found.\n";
   exit 1;
 fi;
+printf "YARN_VERSION:           ${YARN_VERSION}\n";
+
+REPOSITORY_NAME="$(cat ${SETUP_DIR}/repository.Name)";
+if [[ $? != "0" ]]; then
+  printf "[ERROR] ${SETUP_DIR}/repository.Name could not be found.\n";
+  exit 1;
+fi;
+
+DOCKER_REGISTRY_URL="$(cat ${SETUP_DIR}/docker_registry.Url)";
+if [[ $? != "0" ]]; then
+  printf "[ERROR] ${SETUP_DIR}/docker_registry.Url could not be found.\n";
+  exit 1;
+fi;
 
 EXISTENCE_TAG="node-${NODE_VERSION}_yarn-${YARN_VERSION}";
-EXISTENCE_CHECK=$(curl --silent -f -lSL https://index.docker.io/v1/repositories/zephinzer/alpine-node/tags/${EXISTENCE_TAG});
+EXISTENCE_CHECK=$(curl -sSlLf ${DOCKER_REGISTRY_URL}/v1/repositories/${REPOSITORY_NAME}/tags/${EXISTENCE_TAG});
 COMMIT_MESSAGE=$(git log -n 1 --pretty=format:"%B");
 if [[ $? != "0" ]] || [[ $COMMIT_MESSAGE == *"[force build]"* ]]; then
   printf "[BUILDING] TAG:${EXISTENCE_TAG} was NOT found. Building...\n";
